"""initial_schema

Revision ID: 08e8a5710dc6
Revises: 
Create Date: 2026-05-05 02:34:03.103824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e8a5710dc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stock_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('tax_id_last4', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stock_tips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_symbol_id', sa.UUID(), nullable=False),
    sa.Column('tip_summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=6), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['stock_symbol_id'], ['stock_symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol_id', 'effective_date')
    )
    op.create_table('user_watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_symbol_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_symbol_id'], ['stock_symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_symbol_id')
    )
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('line1', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('account_type_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_bank_accounts_profile_id'), 'bank_accounts', ['profile_id'], unique=False)
    op.create_table('account_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pending_deposits', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pending_withdrawals', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overdraft_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_overdraft', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('overdraft_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('requested_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overdraft_requests_account_id'), 'overdraft_requests', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overdraft_requests_account_id'), table_name='overdraft_requests')
    op.drop_table('overdraft_requests')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_bank_accounts_profile_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_table('stock_tips')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stock_symbols')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('account_types')
    # ### end Alembic commands ###
